name: astana_explorer
description: "Astana Explorer Quest App"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

#
# 1. ЗАВИСИМОСТИ ПРИЛОЖЕНИЯ
#
dependencies:
  flutter:
    sdk: flutter
  
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^11.1.0
  permission_handler: ^11.4.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  vector_math: ^2.2.0
  cupertino_icons: ^1.0.8

  # --- ПАКЕТЫ ДЛЯ API ---
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  # ---------------------

#
# 2. ЗАВИСИМОСТИ ДЛЯ РАЗРАБОТКИ
#
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

  # --- ПАКЕТЫ ДЛЯ ГЕНЕРАЦИИ КОДА ---
  build_runner: ^2.4.9
  openapi_generator_plus: ^5.0.0 # <-- ВОТ ОН, В ПРАВИЛЬНОМ МЕСТЕ
  json_serializable: ^6.8.0
  # -------------------------------

flutter:
  uses-material-design: true